### ISSUE TITLE
TwitchのemoteがURL(と閉じタグ)として表示される

### ISSUE THREAD

**Issue by Philmist** [pasta04/unacast#18]
Twitchのemoteが画像として表示されずに、
添付したスクリーンショットのような状態で表示されてしまいます。

使用したのは 6f7e3c33cfb73c4f3209f9e33f0deb0393534ed4 のソースから起動したelectronです。
依存するパッケージはpackage.jsonの記述通りです。

同現象はリリースされているものでも再現します。

![twitch_emote_url](https://user-images.githubusercontent.com/431640/87447313-63e8f800-c635-11ea-95f1-be691f00ba9e.png)

**Comment by Philmist** [comment]
あくまで想像なので別リプライにします。

https://github.com/pasta04/unacast/blob/master/src/main/startServer.ts#L551

```typescript
  const reg = new RegExp("(h?ttps?(://[-_.!~*'()a-zA-Z0-9;/?:@&=+$,%#]+))", 'g');
  const commentText = text.replace(reg, '<span class="url" onClick=\'urlopen("$1")\'>$1</span>');
```
において、Twitchのコメ読みから渡された`<img url="http://example.com/img" />`を
`<img url="<span class="url" onClick='urlopen("http://example.com/img")'>http://example.com/img</span> />`
のように置換しているため、上記のような現象が起きているように思います。

先のウィンドウにおいて、実際に表示されていない画像をクリックすると元のemoteが表示されます。

**Comment by pasta04** [comment]
原因としてはドンピシャで、無理やり回避するようにしました。
実運用上問題になるケースはそうそう無いはず。

https://github.com/pasta04/unacast/commit/7682feef2767bc22fcba87e8255c92d34aa4a26d#diff-11c5840721b754b80eab695b40911fb4R553
https://github.com/pasta04/unacast/releases/tag/ver0.6.3

**Comment by Philmist** [comment]
修正が確認されたのでissueをcloseします。
ありがとうございました。
