### ISSUE TITLE
ニコ生のコメントが途中から取得されない

### ISSUE THREAD

**Issue by bfkbx960** [pasta04/unacast#19]
### 概要
- ニコ生からコメントを取得していたところ、最初のうちは問題なく取得されていたのですが、途中から取得できない現象が発生しました。サーバーを再起動しても同様の現象が発生しました。

### 環境
- Windows10 Home 64bit
- unacast ver0.6.2

### 設定
- したらばの掲示板と、ニコ生と、Twitchから取得する設定をしました。
- 更新間隔5秒で設定をしました。

### 詳細
> ・取得できなくなった大体の配信時間（枠移動や延長してるかも）
  - 枠移動はしてません。延長は枠開始時に5時間30分の延長をしています。
  - 18:06に枠を開始して、18:08のコメントは取得できていますが、18:33のコメントは取得できませんでした。
  - 18:37にサーバーを停止し、再度サーバーを起動しました。
    - 18:38のコメントは取得できていますが、18:50のコメントは取得できませんでした。
> ・ニコニココミュニティIDの下のstatusにエラーが出ててたか
  - こちらきちんと把握はしてませんが、出ていなかったように思います。
  - status:okと最後に取得したコメントの番号が表記されていたと思います。
> ・ログにエラーが出てるか。win10なら以下
  - logs以下にはmain.logとrenderer.logが出力されています。
  - main.logにはニコ生周りでは[error]ログは出ていないように思います。
    - 掲示板のURLなしで起動した場合のエラーや、掲示板のURLをミスって404が発生したエラーはでていました。

**Comment by pasta04** [comment]
定期的にコメントサーバにpingを打つようにしてみました。
6時間枠の配信で試してみましたが、受信できてるように見えるのでこれで試してみてください。

https://github.com/pasta04/unacast/commit/7682feef2767bc22fcba87e8255c92d34aa4a26d#diff-573991f2ebcb64842ac87018c2571aa4R288

https://github.com/pasta04/unacast/releases/tag/ver0.6.3

**Comment by bfkbx960** [comment]
6時間枠で試したところ最後まで取得できました、対応ありがとうございました。
