### ISSUE TITLE
Twitchのemote(絵文字)がそのまま読まれてしまう

### ISSUE THREAD

**Issue by Philmist** [pasta04/unacast#8]
Twitchの場合、emoteがIRCのPRIVMSGで来る際emoteがどういう文字列でどこに含まれているかの情報も来るのですが、キューに入れられる際に処理されていないため、識別文字列のまま読み上げられてしまいます。

dank-twitch-ircではPRIVMSGはPrivmsgMessageのオブジェクトとして表現されますが、オブジェクトのプロパティにemotesがあるので、それを見て置換するなりしてからキューに入れるのが適切かと思います。

参考:
- https://robotty.github.io/dank-twitch-irc/classes/privmsgmessage.html
- https://robotty.github.io/dank-twitch-irc/classes/twitchemote.html

**Comment by pasta04** [comment]
オブジェクトに以下のように含まれているので、
```
  "emotes": [
    {
      "id": "198414",
      "startIndex": 0,
      "endIndex": 9,
      "code": "rtaBanana"
    }
  ],
```
messageTextから、該当するcodeの箇所を以下みたいな感じで置換して出力する。
<img src="https://static-cdn.jtvnw.net/emoticons/v1/${id}/1.0" />

キューへの積み方は検討の必要アリ。

**Comment by pasta04** [comment]
以下でリリースしたので試してみてください
https://github.com/pasta04/unacast/releases/tag/ver0.4.2

**Comment by Philmist** [comment]
絵文字の表示を確認しました。

ただ、Twitchで絵文字に置換後の画像へのURLが読み上げキューに入ってしまっているようです。

**Comment by pasta04** [comment]
すいませんver0.4.3で直したのでそれ以降のバージョンでお願いします。

**Comment by Philmist** [comment]
ありがとうございます。
修正されているのを確認しました。

IssueをCloseします。
